### ISSUE TITLE
scan(): __rsignal(RSIG_SCAN_STREAMBUFFER) returned failure, file unreadable

### ISSUE THREAD

**Issue by rustybrooks** [taviso/loadlibrary#104]
I've been getting this error on every scan in our unit test suite - which normally runs fine.  I can verify the files being sent via the socket are there.  Possibly something wrong on our end up I thought I'd check and see if anyone else had any trouble.

scan(): __rsignal(RSIG_SCAN_STREAMBUFFER) returned failure, file unreadable?

**Comment by taviso** [comment]
Sorry about that, it's caused by an update, I'm working on a solution in #103

**Comment by rustybrooks** [comment]
Ok, cool, no problem.  I just wanted to make sure there wasn't something I could do.
