### ISSUE TITLE
Struggling with 64-bit Ubuntu Linux

### ISSUE THREAD

**Issue by vaq130** [taviso/loadlibrary#17]
I have not been able to compile successfully for a 64-bit system.  

"incompatible with i386:x86-64 output" is the problem obviously.

Have you considered porting it or do you only use on 32-bit systems?

**Comment by taviso** [comment]
I've only tested it on x64, Ubuntu should work perfectly - have you installed the dependencies in the README?

https://github.com/taviso/loadlibrary#dependencies

Can you show me the full error message?
