### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [taviso/loadlibrary#18]
I would like to point out that identifiers like “[`__OPENSCAN_H`](https://github.com/taviso/loadlibrary/blob/aa445174ce34f2f6dddd0763d374a81747ac0078/include/openscan.h#L1 "Update candidate")” and “[`__rsignal`](https://github.com/taviso/loadlibrary/blob/aa445174ce34f2f6dddd0763d374a81747ac0078/mpclient.c#L62 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by taviso** [comment]
We're doing a lot of things that are gcc and Linux specific.

In particular, `__rsignal` is an export from a third party DLL that we can't control.

**Comment by elfring** [comment]
* You [could delete leading underscores from affected identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?"), couldn't you?
* How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by taviso** [comment]
This whole project is built on undefined behaviour :)

There is no defined way to mmap() a DLL on Linux, it's not going to happen. Modern GCC on Linux i386/x64 is supported, and anything that stops that working is a bug. Making it use defined behaviour is definitely not a goal and is definitely not possible, how are you going to setup segment selectors on Linux without undefined behaviour?

**Comment by elfring** [comment]
I suggest to distinguish a bit more between details which affect the desired standard compliance for the mentioned programming interfaces.

**Comment by taviso** [comment]
No compliance is desired.

**Comment by elfring** [comment]
You depend also on compliance to some degree. I imagine that it would be very hard to clarify desirable software behaviour otherwise.

**Comment by taviso** [comment]
Yes, but only to the degree that it actually works on modern gcc on Linux i386/x86_64.

If you can show a case where it doesn't work as intended on that configuration, please reopen.

**Comment by elfring** [comment]
Please reopen this issue so that software development concerns can be reduced a bit more around undefined behaviour.
