### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [taviso/loadlibrary#19]
Would you like to add more error handling for return values from functions like the following?
- [fgetc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fgetc.html "Get a byte from a stream.") ⇒ [process_extra_exports](https://github.com/taviso/loadlibrary/blob/aa445174ce34f2f6dddd0763d374a81747ac0078/peloader/extra.c#L40)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator in a stream.") ⇒ [ReadStream](https://github.com/taviso/loadlibrary/blob/aa445174ce34f2f6dddd0763d374a81747ac0078/mpclient.c#L90)

**Comment by taviso** [comment]
Do you have a test case where this fails?

If not, I'm not too worried about this.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by taviso** [comment]
Not really, huge amounts of the imports silently return success. This is intentional, designed to satisfy the minimum functional requirements.

**Comment by elfring** [comment]
Did you test to read any data from a file like /dev/null accidentally?

**Comment by taviso** [comment]
Sigh, I just tested and symlinked it to `/dev/null`, it works fine - please verify something fails before filing issues!!

I appreciate your help, but standards compliance is not a goal. Please only open a bug if you've got a  **reproducible** test case for gcc on Linux x86_64.

I'm locking this conversation for now, but don't be afraid to open a new issue if you have a **reproducible** test case.
