### ISSUE TITLE
problem building

### ISSUE THREAD

**Issue by blacktop** [taviso/loadlibrary#2]
I apologize for this noob-ish issue

```bash
pe_linker.c: In function 'setup_nt_threadinfo':
pe_linker.c:650:17: error: '__NR_modify_ldt' undeclared (first use in this function)
     if (syscall(__NR_modify_ldt, LDT_WRITE, &pebdescriptor, sizeof pebdescriptor) != 0) {
                 ^
pe_linker.c:650:17: note: each undeclared identifier is reported only once for each function it appears in
<builtin>: recipe for target 'pe_linker.o' failed
make[1]: Leaving directory '/windef/loadlibrary/peloader'
make[1]: *** [pe_linker.o] Error 1
make: *** [peloader] Error 2
```

My build env is [here](https://github.com/maliceio/malice-windows-defender/blob/master/Dockerfile)

you are THE MAN btw 😄

**Comment by taviso** [comment]
Hmm, It should be in `/usr/include/asm/unistd_32.h` which gets included from `asm/unistd.h`.

I see your script does `ln -s /usr/include/asm-generic /usr/include/asm`, instead of using the arch ones.

If you really need to do that for some reason, you can probably add `-D__NR_modify_ldt=123` to the Makefile CFLAGS in the peloader directory...

**Comment by blacktop** [comment]
If I don't include the `ln -s` I get the following error:

```bash
cc -O3 -march=native -ggdb3 -m32 -std=gnu99 -fshort-wchar -Wno-multichar -Iinclude -DNDEBUG -D_GNU_SOURCE -I. -Iintercept -Ipeloader  -c -o mpclient.o mpclient.c
mpclient.c:31:24: fatal error: asm/unistd.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'mpclient.o' failed
make: *** [mpclient.o] Error 1
```

**Comment by taviso** [comment]
Hmm, does `apt-get install linux-libc-dev:i386` provide it? (I'm not on Ubuntu right now)

**Comment by taviso** [comment]
I tested on Ubuntu, I think `apt-get install libc6-dev:i386 gcc-multilib` is enough. I added that to the README.

**Comment by thebetterjort** [comment]
@blacktop You adding to this to your malice?

**Comment by blacktop** [comment]
Those packages are not found on ubuntu.  

I made a small pull request with the packages that I did find that I think correlate with what you need?

**Comment by blacktop** [comment]
@thebetterjort yes I want to if it works.  

I guess I probably need to use the GPL license on that plugin then?

@taviso what is your understanding of GPL with respects to me running your tool in a docker container, but not changing it in any way?

**Comment by blacktop** [comment]
I appended you license to mine, please let me know if that is satisfactory?

and again @taviso 

you are THE MAN!!!

**Comment by taviso** [comment]
Thanks, I guess we must be on different Ubuntu versions and the packages were renamed! I'll figure out which versions need which packages.

It's fine to run it and make any changes you like, the GPL only matters if you want to share your changes with other people, then the changes have to be GPL as well - that's basically it!

**Comment by jtlz2** [comment]
@taviso @blacktop Agree! I'm just doing a straight build of this on Ubuntu and still getting the original error - but now I can't find the relevant package:

E: Unable to locate package libc6-dev:i386

**Comment by jtlz2** [comment]
Sorry - just `apt-get install gcc-multilib` beat this one

**Comment by jtlz2** [comment]
Fixed via @blacktop 's Docker image - thanks + sorry!
