### ISSUE TITLE
Dll loading crashes in __CRT_INIT@12

### ISSUE THREAD

**Issue by jrmuizel** [taviso/loadlibrary#23]
The __CRT_INIT@12 does:
mov eax, dword ptr fs:[18h]
mov eax, dword ptr [eax+4]

The load from fs:[18h] gives 0 in loadlibrary and a valid pointer on windows

**Comment by jrmuizel** [comment]
fs:[18h] is supposed to be the address of the TEB

**Comment by taviso** [comment]
I think this is issue #9, did you compile your kernel with the option `CONFIG_MODIFY_LDT_SYSCALL` disabled?

I should detect that and print an informative error message, I suppose.

**Comment by jrmuizel** [comment]
modify_ldt works fine for me. This load works fine: 'mov eax, dword ptr fs:[18h]'. It's the subsequent dereference that crashes.

**Comment by jrmuizel** [comment]
It looks like ThreadInfo.Self is not set to a valid value.

**Comment by taviso** [comment]
Ah, I see. You're right, the TEB implementation is pretty minimal right now, I guess that's trying to find the stackbase? I'll expand it a bit.

**Comment by jrmuizel** [comment]
The following seems to be enough to avoid the crash for me:

```patch
diff --git a/peloader/pe_linker.c b/peloader/pe_linker.c
index 57c902a..b4d9ede 100644
--- a/peloader/pe_linker.c
+++ b/peloader/pe_linker.c
@@ -647,6 +647,8 @@ bool setup_nt_threadinfo(PEXCEPTION_HANDLER ExceptionHandler)
         ThreadInfo.ExceptionList    = &ExceptionFrame;
     }

+    ThreadInfo.Self = &ThreadInfo;
+
     if (syscall(__NR_modify_ldt, LDT_WRITE, &pebdescriptor, sizeof pebdescriptor) != 0) {
         return false;
     }
```

**Comment by taviso** [comment]
Thanks, LGTM, I'll just make that change.

**Comment by taviso** [comment]
Thanks!
