### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by vendforce** [taviso/loadlibrary#30]
installing from aur

Cloning into bare repository '/user/Downloads/loadlibrary-git/loadlibrary'...
remote: Counting objects: 228, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 228 (delta 0), reused 2 (delta 0), pack-reused 223
Receiving objects: 100% (228/228), 807.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (73/73), done.
  -> Found mpam-fe.exe
==> Validating source files with md5sums...
    loadlibrary ... Skipped
    mpam-fe.exe ... Passed
==> Extracting sources...
  -> Creating working copy of loadlibrary git repo...
Cloning into 'loadlibrary'...
done.
  -> Extracting mpam-fe.exe with bsdtar
mpengine.dll: LZX decompression failed (-25)
bsdtar: Error exit delayed from previous errors.
==> ERROR: Failed to extract mpam-fe.exe
    Aborting...

**Comment by taviso** [comment]
I'm not sure what aur is, but it looks like you're using tar to extract `mpam-fe.exe`, but it's a cabinet file and requires `cabextract`. Does that help?

**Comment by vendforce** [comment]
aur is the arch repos 
#https://aur.archlinux.org/packages/loadlibrary-git/

pacaur -Ss cabextract  # search for install
community/cabextract 1.6-1 [installed]
    A program to extract Microsoft cabinet (.CAB) files

I have cabextract installed is there any other reason it wont install

I've also tried downloading from git and doing make & make install same error

**Comment by taviso** [comment]
When you type `make` it says  `LZX decompression failed`? I've never seen that error before, I can't really imagine where it's coming from...

Can you paste the full output of `make`?

**Comment by vendforce** [comment]
sorry the compress error isn't happening with git but it seems to have problems with the library

#### compile using make
https://pastebin.com/tVXFUqUt

#### execute mpclient output 
./mpclient /user/textfile 
pe_load_library(): failed to open pe library engine/mpengine.dll, No such file or directory
main(): You must add the dll and vdm files to the engine directory

**Comment by vendforce** [comment]
mpengine.dll is missing from the engine folder

### this is all that is listed in the engine folder
createmap.idc  README.md

**Comment by taviso** [comment]
It looks like it's working, you just need to download this file which contains the engine and virus signatures:

http://go.microsoft.com/fwlink/?LinkID=121721&arch=x86

Then run `cabextract` to unpack it, and then it should work.

**Comment by vendforce** [comment]
cabextract mpam-fe.exe 
mpam-fe.exe: no valid cabinets found

All done, errors in processing 1 file(s)

**Comment by vendforce** [comment]
ok got it working 

https://go.microsoft.com/fwlink/?LinkID=121721&arch

I removed the x86

**Comment by taviso** [comment]
I dunno, maybe the download was corrupted or interrupted - try downloading it again.

```
$ file mpam-fe.exe 
mpam-fe.exe: PE32 executable (GUI) Intel 80386, for MS Windows
$ du -m mpam-fe.exe 
121	mpam-fe.exe
```

Make sure it looks sane, it should be about 120MB and a PE32 file...otherwise, maybe you have an old version of cabextract? What version?

**Comment by taviso** [comment]
Ah, you got it working 👍 :-)
