### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by vendforce** [taviso/loadlibrary#31]
./mpclient /user/textfile  

main(): Scanning /root/textfile...
EngineScanCallback(): Scanning input
EngineScanCallback(): Threat Virus:DOS/EICAR_Test_File identified.

#### is there a way to only either grep or only print part of the output like print only 'Treat Virus' I've tried the below and other grep methods but cant seem to limit the output

./mpclient /user/textfile  > /dev/null | awk -F ":" '{print $2}'  ## does'nt work

**Comment by taviso** [comment]
I should add better options for output control. For now, your regex looks like it should work, just use `2>&1` instead of `> /dev/null`.
