### ISSUE TITLE
mpclient error

### ISSUE THREAD

**Issue by 4n6analist** [taviso/loadlibrary#37]
Pulled latest:
:~/loadlibrary$ git pull
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 15 (delta 12), reused 14 (delta 12), pack-reused 1
Unpacking objects: 100% (15/15), done.
From https://github.com/taviso/loadlibrary
   0847ba8..45296de  master     -> origin/master
Updating 0847ba8..45296de
Fast-forward
 genmapsym.sh                 |  2 +-
 peloader/winapi/Locale.c     |  8 ++++----
 peloader/winapi/Strings.c    | 44 ++++++++++++++++++++++++++------------------
 peloader/winapi/SystemTime.c |  8 ++++++++
 4 files changed, 39 insertions(+), 23 deletions(-)

Tried to scan file MD5 b3f3f1e82faee94eb043d27c8ec87a87
:~/loadlibrary$ ./mpclient /yarfukt/418506f1a541fdc1cc6f42a596dcd76ce13ba9d151830b4cb784bde6f3b82389 
MultiByteToWideChar(): Unsupported Conversion Flags 0x1
MultiByteToWideChar(): Unsupported Conversion Flags 0x1
MultiByteToWideChar(): Unsupported Conversion Flags 0x1
MultiByteToWideChar(): Unsupported Conversion Flags 0x1
MultiByteToWideChar(): Unsupported Conversion Flags 0x1
MultiByteToWideChar(): Unsupported Conversion Flags 0x1
Segmentation fault (core dumped)

**Comment by taviso** [comment]
This looks like a bug I fixed recently, is it possible you forgot to type `make` after the pull?

**Comment by 4n6analist** [comment]
sleep is a wonderful thing :) You are on top of it as usual.  works after make
