### ISSUE TITLE
Latest update of mpam-fe.exe  causes segmentation fault

### ISSUE THREAD

**Issue by 4n6analist** [taviso/loadlibrary#39]
mofugly@yomoma:~/loadlibrary$ ./mpclient ~/scanfiles/files/f823a2f7cd40b8e86ec70b71a5a68cbb
main(): Scanning /home/mofugly/scanfiles/files/f823a2f7cd40b8e86ec70b71a5a68cbb...
Segmentation fault

**Comment by taviso** [comment]
Thanks for letting me know, I'm investigating right now.

**Comment by taviso** [comment]
I think I see the bug, hopefully it's fixed now. Thanks for letting me know!

**Comment by 4n6analist** [comment]
Thanks for the quick fix as usual!
