### ISSUE TITLE
can u tell me why should hook _strtod function

### ISSUE THREAD

**Issue by maldiohead** [taviso/loadlibrary#4]
I am confused why should hook this function

**Comment by taviso** [comment]
Hey, the javascript engine uses strtod() to implement window.parseFloat(), so I send all output to window.parseFloat(), and then I can see it by hooking strtod().

If it's output I want (prefixed with a magic string, see the log() wrapper at the top of mpscript.c), I print it!

Hope that helps!

**Comment by maldiohead** [comment]
thanks for ur help
