### ISSUE TITLE
version numbers

### ISSUE THREAD

**Issue by vendforce** [taviso/loadlibrary#45]
https://www.microsoft.com/en-us/wdsi/definitions

Version: 1.261.1314.0
Released: Feb 17,2018 10:31 PM UTC

after downloading the new file and extracting the file into the engine folder the version I'm getting is

exiftool mpengine.dll | grep 'Product Version Number'

Product Version                 : 1.1.14500.5

why isn't the numbers the same ?

I've tried deleting all the files in the engine folder and then using cabextract but the version number is still the same

**Comment by taviso** [comment]
The engine version number is different from the definitions version (the latter could just be a data/signature update, but no changes to the code).

**Comment by vendforce** [comment]
I have a windows test machine , I opening Microsoft security essentials and updated it and it has the exact viruses definitions that's listed on  https://www.microsoft.com/en-us/wdsi/definitions

My problem is I wrote a script to check for version updates and if they numbers were not the same it would download the new mpam-fe.exe and extract into /usr/lib/loadlibrary/engine before it scanned the file

it was working fine until now, when the update numbers were the same it would just sacn the file when they were not the same it would download the definitions

is it not a problem with mpengine.dll and extracting the correct version number ??

**Comment by vendforce** [comment]
There is definitely a problem somewhere in loadlibrary the last couple of days there has been new virus definitions on https://www.microsoft.com/en-us/wdsi/definitions i.e versions  yet when I download then today and extract then into my home folder and check the version its the same as it was when I reported this bug


the version on webpage should match the version on the mpengine.dll


on the 17th the version on the Microsoft page was Version: 1.261.1314.0
today its 1.261.1393.0


yet when I download the latest version and extract to my home folder and do
exiftool mpengine.dll | grep 'Product Version Number'  1.1.14500.5

its the same version number as before 

PLEASE FIX !!!!!

**Comment by taviso** [comment]
Everything looks correct to me, I don't see the problem.

The latest version on that page says `1.261.1398.0` for me, and the link points to 
`https://definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.261.1398.0/x86/mpam-fe.exe`. If I examine that file:

```
Product Version                 : 1.261.1398.0
Engine Version                  : 1.1.14500.5
```
Those numbers seem correct, and if I extract it and examine the engine:

```
File Version                    : 1.1.14500.5 (5ed17a8d71195f7dd09ac85d18671d0876764dd1)
Product Version                 : 1.1.14500.5
```

This all seems correct to me, what am I missing?

**Comment by vendforce** [comment]
why isnt the file version changing ?? it should change i.e when updates are added 
so if product version/file version doesnt change how can there be updates ?? the file has to increase

its at 1.1.14500.5 and still at that number since a couple of days ago , but yet there has been updates and the version number increases on the microsoft site as I showed on the last reply 

As I said my script was working fine and never failed up until now , as it depends on matching the file version number but its not changing any more ? are you telling me from now on it will always be 1.1.14500.5 but its still get updates because this was never the case , if it was I wouldnt have bothered writing a script to check for updates as it would only see the same number

**Comment by taviso** [comment]
The version number on the `mpam-fe.exe` file will change every version. The version on the `mpengine.dll` only changes /sometimes/ (once every few months). The `mpam-fe.exe` file contains the engine dll *and* vdm files, which contain data, new signatures, and so on. 

An update might contain a new engine, but it might not, it might only need new signatures.

I don't think anything has changed, it's always worked like this.

**Comment by vendforce** [comment]
your wrong ..  as I said I wrote a script for it !!! it was working now its not 

before when you did exiftool you got Product Version                 : 1.261.1xxx.0
now your just getting  this same number all them time               1.1.14500.5
 

Im telling you there is something wrong and yet you think there is not ?? its a s plain as day

**Comment by taviso** [comment]
I downloaded several versions of `mpengine.dll` from our archive to check, and they all work like this. What was the last version of `mpengine.dll` you have where it worked like this? (It will have to be from 2015 at least, because I checked every version from 2017 and 2018, and one from 2016-05-26).

Are you sure you somehow didn't change your script to check mpengine.dll, but it used to check mpam-fe.exe? That would explain it, and that would have worked.

**Comment by taviso** [comment]
Sure, show me the script.

**Comment by vendforce** [comment]
opps ... sorry I must have editied the script by mistake 
checking with mpam-fe.exe gives you 

exiftool mpam-fe.exe | grep 'Product Version Number'
Product Version Number          : 1.261.1507.0

sorry my bad !!! 

mpam-fe.exe will give you the definitions
mpengine.dll with give you the version 

once again sorry about that, I fixed the script and its working again
