### ISSUE TITLE
Starting mpclient takes 11 seconds. As expected?

### ISSUE THREAD

**Issue by sanderjo** [taviso/loadlibrary#5]
What a cool project!

EDIT: it's not the scanning that takes 11 seconds, but also just starting mpclient without parameters and thus no scanning at all:

```
sander@haring:~/git/loadlibrary$ time ./mpclient
main(): The map file wasn't found, symbols wont be available
main(): usage: ./mpclient [filenames...]

real    0m12.162s
user    0m8.300s
sys     0m1.188s
sander@haring:~/git/loadlibrary$
```

OLD:
I have a question: scanning EICAR.COM takes 11 seconds. Is that normal & as expected?

```
sander@haring:~/git/loadlibrary$ time ./mpclient eicar.com
main(): The map file wasn't found, symbols wont be available
main(): Scanning eicar.com...
EngineScanCallback(): Scanning input
EngineScanCallback(): Threat Virus:DOS/EICAR_Test_File identified.

real    0m11.595s
user    0m7.692s
sys     0m1.148s
```
FWIW: CPU is an Intel(R) Xeon(R) CPU E5335, RAM is 512MB.

**Comment by sanderjo** [comment]
With some poor man's debugging, I found where the 11 second delay is: in the 
`if (__rsignal(&KernelHandle, RSIG_BOOTENGINE, &BootParams, sizeof BootParams) != 0)
`

Logging where the delay occurs:
```
Point 300
Current time: 1495617002.898 seconds since the Epoch
Point 310
Current time: 1495617014.604 seconds since the Epoch
```
Code part in mpclient.c (with my timestamping):
```
printf("Point 300\n");
print_current_time_with_ms();

    if (__rsignal(&KernelHandle, RSIG_BOOTENGINE, &BootParams, sizeof BootParams) != 0) {
        LogMessage("__rsignal(RSIG_BOOTENGINE) returned failure, missing definitions?");
        LogMessage("Make sure the VDM files and mpengine.dll are in the engine directory");
        return 1;
    }

printf("Point 310\n");
print_current_time_with_ms();
```

**Comment by taviso** [comment]
Hey, yes - that's expected, it takes a really long time to load the definition files and initialize the engine, but once it's loaded you scan many files. This is a common design in antivirus engines, on Windows msmpeng loads the definitions once at startup and then accepts RPCs to scan files.

**Comment by sanderjo** [comment]
Thank you for your reply.

> once it's loaded you scan many files. 

Just checking: only the files that were specified on the command line at start up, right? You can't start mpclient, and then later on feed it more files to be scanned?

> This is a common design in antivirus engines, on Windows msmpeng loads the definitions once at startup and then accepts RPCs to scan files.

Yes, clear. Would such a setup be technically possible on Linux? So: start mpclient_rpc_server, and via RPC feed it filenames to be scanned (like `mpclient_rpc_client localhost /my/path/to/eicar.com`)?

**Comment by taviso** [comment]
> Just checking: only the files that were specified on the command line at start up, right? You can't start mpclient, and then later on feed it more files to be scanned?

Yep, exactly.

> Yes, clear. Would such a setup be technically possible on Linux?

Sure, in fact it would be quite easy, just a few lines of code for a simple version :)

**Comment by sanderjo** [comment]
OK, thank you!
