### ISSUE TITLE
Latest antimalware definitions do not work.

### ISSUE THREAD

**Issue by worlvlhole** [taviso/loadlibrary#52]
FYI:
The version breaks loadlibrary. 
`Product Version Number          : 1.1.15300.6`

```
 ./mpclient README.md 
main(): Scanning README.md...
mpclient: function at 0xf69e513c attempted to call an unknown symbol
Trace/breakpoint trap (core dumped)
```

**Comment by taviso** [comment]
Thanks for letting me know, investigating now.

**Comment by taviso** [comment]
I see the problem, commit incoming...

(if you have time to verify the fix works for you, would appreciate it!)

**Comment by worlvlhole** [comment]
Awesome! Thank you very much. 

I confirmed that it now works.
