### ISSUE TITLE
finding old version of mpengine.dll

### ISSUE THREAD

**Issue by mxmssh** [taviso/loadlibrary#54]
Hi Tavis,

Thank you for the excellent tool. I am trying to find mpengine.dll with debug symbols. The latest version (September) doesn't have them and I don't want to wait when MS release it. So I am looking for August version of mpengine but it seems to be very hard to find it. Could you recommend me some technique/place to look for old MS libraries? I tried to download old release of Windows 10 (1803, August build) but they supply it with March version of mpengine.

Thank you in advance.

**Comment by mxmssh** [comment]
Yes! That's what I was thinking, to get a VT account. Thank you! Thought you might have some other approach.

**Comment by wangkai0351** [comment]
Hi Maksim, 
When I started to research MPENGINE, I found a file-sharing website created by a cyber security researcher that contained historical versions of the main DLLs in Windows OS.https://winbindex.m417z.com/
