### ISSUE TITLE
broken mpclient after update

### ISSUE THREAD

**Issue by 4g3n7** [taviso/loadlibrary#57]
mpclient: function at 0xf616cf78 attempted to call an unknown symbol
Trace/breakpoint trap

**Comment by taviso** [comment]
Thank you for the report, do you have the input you were trying to scan? (e.g. is it a hash I can lookup on virustotal)

Thanks!

**Comment by taviso** [comment]
I've tried a few sample inputs and it seems to still be working for me, but it might be a particular scanner you were using.

**Comment by 4g3n7** [comment]
mea culpa.  I nuked the engine directory and grabbed a new mpam-fe and now it is working  again.  Something was not jiving.

Thanks for the great code and quick response Tavis.

**Comment by taviso** [comment]
No problem! Glad it's working.
