### ISSUE TITLE
Segm. fault

### ISSUE THREAD

**Issue by bsbhro** [taviso/loadlibrary#6]
Hi, what a cool project! It will make scalds in Redmont (one commented, who brought me here :-)

Can you use this error message? I can not. Thank you
![bildschirmfoto_2017-05-24_14-04-24](https://cloud.githubusercontent.com/assets/2652120/26403830/efd099ba-408f-11e7-8eab-3f5717b25d31.png)

**Comment by taviso** [comment]
Thanks, could you show me the output of the gdb command `x/20hx lpSrc` and `x/s CreateAnsiFromWide(lpSrc)`?

**Comment by bsbhro** [comment]
Here it is
![bildschirmfoto_2017-05-24_16-00-12](https://cloud.githubusercontent.com/assets/2652120/26407025/35d70d18-409a-11e7-88c6-74aef5e656b6.png)

**Comment by taviso** [comment]
Well, that's confusing. It seems like it should work, and that version works fine for me.

I'll think about what could have gone wrong.

**Comment by taviso** [comment]
Can you run these commands as well?

`x/i $pc` and `i r`

**Comment by bsbhro** [comment]
No hurry please :-)
![bildschirmfoto_2017-05-24_16-15-29](https://cloud.githubusercontent.com/assets/2652120/26407808/65edae6a-409c-11e7-9fb7-e330286b0cf7.png)

**Comment by taviso** [comment]
That is really weird, it's using `movaps` which has alignment requirements, but then didn't align the stack.

`esp+0x3c` would be `0xffffbdf4`, which is obviously not 16 byte aligned. I would have expected it to either force alignment of the structure, or used `movups`, which has no alignment requirement.

Is this an unusual compiler? Like, pre-release gcc or something? 😕

**Comment by bsbhro** [comment]
It's the standard 'gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406'. The make was fast and successful.

**Comment by taviso** [comment]
Ah-ha, I googled it a bit, someone else figured out the problem here:

http://www.peterstock.co.uk/games/mingw_sse/

I think his solution will work, I'll just add `-mstackrealign` to the Makefile.

**Comment by taviso** [comment]
Thanks for helping to debug this, that was unexpected!

**Comment by bsbhro** [comment]
I pulled it and ... you got it. Thanks a lot :-)
![bildschirmfoto_2017-05-24_16-43-49](https://cloud.githubusercontent.com/assets/2652120/26409285/6591cf4c-40a0-11e7-8da4-a84550050471.png)
