### ISSUE TITLE
More Seg Faults still not working ?? 

### ISSUE THREAD

**Issue by vendforce** [taviso/loadlibrary#67]
[loadlibrary]# gdb -q ./mpclient 
Reading symbols from ./mpclient...done.
(gdb) r test.exe
Starting program: /home/user/mpclient test.exe

Program received signal SIGSEGV, Segmentation fault.
0xf689a950 in ?? ()

LAST SEG FAULT :  0xf6873950 in ?? ()
LATEST SEG FAULT  0xf689a950 in ?? ()

**Comment by taviso** [comment]
Sorry for the delay on this, fixing the TEB was easy, but there were more errors that I need to track down.

Give me a few more days to get to this, I'm on it 😃

**Comment by vendforce** [comment]
No problem, appreciate the update thanks
