### ISSUE TITLE
signal: aborted

### ISSUE THREAD

**Issue by drwpeng** [taviso/loadlibrary#70]
Hi taviso,
* After you fix #65, I got **signal: aborted**.
* The code I am using is https://github.com/malice-plugins/windows-defender, which uses your program as a subroutine.  
* The return of the subroutine is **_signal: aborted_**
* Please take a look.

**Comment by taviso** [comment]
Does it depend on the file you're trying to scan? I can't reproduce it here..

**Comment by drwpeng** [comment]
* I add some out info in scan.go
```
func RunCommand(ctx context.Context, cmd string, args ...string) (string, error) {
	var c *exec.Cmd

	log.Info("cmd::", cmd, ", args::", args)
	if ctx != nil {
		c = exec.CommandContext(ctx, cmd, args...)
	} else {
		c = exec.Command(cmd, args...)
	}
	var (
		output []byte
		err    error
	)
	output, err = c.CombinedOutput()
	if err != nil {
		log.Info("c Args:", c.Args)
		log.Info("c Path:", c.Path)
		log.Info("c processstate:", c.ProcessState)
		log.Info("RunCommand: ", string(output), err.Error())
		return string(output), err
	}

	// check for exec context timeout
	if ctx != nil {
		if ctx.Err() == context.DeadlineExceeded {
			return "", fmt.Errorf("command %s timed out", cmd)
		}
	}

	return string(output), nil
}
```
**output:**
`
time="2019-08-21T05:10:30Z" level=info msg="cmd::./mpclient, args::[/malware/12d1e796a26437138ca852fede263f133fa2792ed3af6ace5ec25a5f0749d115]"
time="2019-08-21T05:10:30Z" level=info msg="c Args:[./mpclient /malware/12d1e796a26437138ca852fede263f133fa2792ed3af6ace5ec25a5f0749d115]"
time="2019-08-21T05:10:30Z" level=info msg="c Path:./mpclient"
time="2019-08-21T05:10:30Z" level=info msg="c processstate:signal: aborted"
time="2019-08-21T05:10:30Z" level=info msg="RunCommand: signal: aborted"
`
**Then**
[wpeng@localhost ~]$ docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
breakingbad/windows-defender               0.1.0               c5dc0444b13e        2 hours ago         930MB
breakingbad/windows-defender               latest              c5dc0444b13e        2 hours ago         930MB

[wpeng@localhost ~]$ docker run breakingbad/windows-defender /bin/bash
time="2019-08-21T05:22:54Z" level=info msg="filepath:/bin/bash"
time="2019-08-21T05:22:54Z" level=info msg="cmd::./mpclient, args::[/bin/bash]"
state..........: signal: aborted
time="2019-08-21T05:22:54Z" level=info msg="c Args:[./mpclient /bin/bash]"
time="2019-08-21T05:22:54Z" level=info msg="c Path:./mpclient"
time="2019-08-21T05:22:54Z" level=info msg="c processstate:signal: aborted"
time="2019-08-21T05:22:54Z" level=info msg="RunCommand: signal: aborted"
time="2019-08-21T05:22:54Z" level=info msg="./mpclient:/bin/bash"
time="2019-08-21T05:22:54Z" level=fatal msg="signal: aborted" category=av path=/bin/bash plugin=windows_defender

**Comment by taviso** [comment]
Hmm, I found that file on VirusTotal, it seems to work okay here.

```
$ ./mpclient 12d1e796a26437138ca852fede263f133fa2792ed3af6ace5ec25a5f0749d115 
main(): Scanning 12d1e796a26437138ca852fede263f133fa2792ed3af6ace5ec25a5f0749d115...
EngineScanCallback(): Scanning input
EngineScanCallback(): Packer nUFS_svfohigh identified.
EngineScanCallback(): Scanning input->(RarSfx)
EngineScanCallback(): Packer nUFS_rar identified.
EngineScanCallback(): File is encrypted.
```

Sorry, I'm not a docker expert, is it possible to get a shell inside the image and run it under gdb?

**Comment by drwpeng** [comment]
I add some printf() in mpclient.c,
```
    printf("9\n");

    BootParams.ClientVersion = BOOTENGINE_PARAMS_VERSION;
    BootParams.Attributes    = BOOT_ATTR_NORMAL;
    BootParams.SignatureLocation = L"engine";
    BootParams.ProductName = L"Legitimate Antivirus";
    EngineConfig.QuarantineLocation = L"quarantine";
    printf("a\n");
    EngineConfig.Inclusions = L"*.*";
    EngineConfig.EngineFlags = 1 << 1;
    BootParams.EngineInfo = &EngineInfo;
    BootParams.EngineConfig = &EngineConfig;
    KernelHandle = NULL;

    printf("b\n");
    if (__rsignal(&KernelHandle, RSIG_BOOTENGINE, &BootParams, sizeof BootParams) != 0) {
        LogMessage("__rsignal(RSIG_BOOTENGINE) returned failure, missing definitions?");
        LogMessage("Make sure the VDM files and mpengine.dll are in the engine directory");
        return 1;
    }
    printf("10\n");
```

Then I run mpclient in container:
```
root@3d859d4ce047:/loadlibrary# ./mpclient
9
a
b
Aborted
```
There seems to be a problem here?
 **__rsignal(&KernelHandle, RSIG_BOOTENGINE, &BootParams, sizeof BootParams)**

**Comment by drwpeng** [comment]
Is it a problem with **KernelHandle**? It's NULL

**Comment by taviso** [comment]
It's supposed to be NULL, the engine fills it in with a pointer.

Can you show me the output of `exiftool mpengine.dll`? It must be a version I haven't tested.

**Comment by drwpeng** [comment]
```
[wpeng@localhost oldmpam-fe]$ exiftool mpengine.dll
ExifTool Version Number         : 11.63
File Name                       : mpengine.dll
Directory                       : .
File Size                       : 11 MB
File Modification Date/Time     : 2019:08:14 12:58:40+08:00
File Access Date/Time           : 2019:08:14 12:58:40+08:00
File Inode Change Date/Time     : 2019:08:22 11:15:26+08:00
File Permissions                : rw-r--r--
File Type                       : Win32 DLL
File Type Extension             : dll
MIME Type                       : application/octet-stream
Machine Type                    : Intel 386 or later, and compatibles
Time Stamp                      : 2019:07:05 11:05:39+08:00
Image File Characteristics      : Executable, 32-bit, DLL
PE Type                         : PE32
Linker Version                  : 14.20
Code Size                       : 10321920
Initialized Data Size           : 952832
Uninitialized Data Size         : 0
Entry Point                     : 0x27fa40
OS Version                      : 10.0
Image Version                   : 10.0
Subsystem Version               : 6.0
Subsystem                       : Windows command line
File Version Number             : 1.1.16200.1
Product Version Number          : 1.1.16200.1
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Windows NT 32-bit
Object File Type                : Dynamic link library
File Subtype                    : 0
Language Code                   : English (U.S.)
Character Set                   : Unicode
Company Name                    : Microsoft Corporation
File Description                : Microsoft Malware Protection Engine
Internal Name                   : mpengine
Legal Copyright                 : © Microsoft Corporation. All rights reserved.
Original File Name              : mpengine.dll
Product Name                    : Microsoft Malware Protection
File Version                    : 1.1.16200.1 (915bc1a84c825ac6c2975ddd59e00a94581e1dbe)
Product Version                 : 1.1.16200.1

```

**Comment by taviso** [comment]
Confusing, I have that exact version. I can't really imagine what's going wrong and can't reproduce it here.

I really need to see a backtrace in gdb to figure out the problem, do you have any way of getting a coredump or running it under gdb?

**Comment by drwpeng** [comment]
hi, 
I tried to use gdb in the container, but I investigated it online for a day and tried the following. The program could not stop at the breakpoint.
* set disable-randomization off
* set follow-fork-mode child
* set non-stop on
* Remove the optimized parameters from the Makefile
Do you have any suggestions for these?

In addition, at #65, there is a core file, but now there is no core file generation.

Finally, happy weekend.

**Comment by taviso** [comment]
I just can't imagine what the problem is, there are only a few ways it can abort:

1. Memory corruption detected by the allocator, but it would print an error to the console unless you had set MALLOC_CHECK_ to a non-default value, and presumably you would have mentioned either the error message or that you had set that.
2. An assert() failed, but these are disabled by default and I assume you would have said if you had enabled them in the Makefile.
3. One of only two or three places that I call abort(), but these are things like calling CreateFile with a flag I don't recognize, which surely wouldn't be unique to you.
4. The exception handling logic failed...but I'm reasonably confident that code is correct, and I would be able to reproduce it.

Can you show me the output from gdb you can get? I understand you can't get breakpoints to work, but just knowing where the abort is coming from would be helpful.

Just like this:

```
$ gdb --args ./mpclient
```

Keep typing `r` until it crashes, then `x/i $pc` and `bt`

**Comment by taviso** [comment]
None of the Microsoft code can abort(). If the mpengine code goes wrong, it mostly uses a Windows thing called "fastfail", which just calls `int 0x29`.

On Linux, that just causes a `SIGSEGV`, not a `SIGABRT`, so it can't be that.

Is there anything in the host dmesg? I'm wondering if this is like a SELinux policy violation or something, although I would expect that to either just cause a permission denied, or a `SIGKILL`....but who knows.

In gdb please also type `p $_siginfo` after the crash, just in case...

**Comment by drwpeng** [comment]
Yes, this is it. 
 It run successfully when I add **sigprocmask** to the whitelist. 
Thank you all.
