### ISSUE TITLE
Breaking change in the newest engine (2019-10-22): missing definitions?

### ISSUE THREAD

**Issue by dstruck** [taviso/loadlibrary#73]
There seems to be a breaking change in the newest engine (2019-10-22):

```
$ ./mpclient test.txt
main(): __rsignal(RSIG_BOOTENGINE) returned failure, missing definitions?
main(): Make sure the VDM files and mpengine.dll are in the engine directory
```

**Comment by egoitzau** [comment]
Same here, can it be broken now?

**Comment by taviso** [comment]
Sorry for the delay, I see the problem. The latest builds all require CALG_SHA_256 support, until this month it always requested CALG_SHA1. So when it asks how big a hash is, I tell it 20 bytes (160 bits) for a SHA-1 hash, and it gets very confused.

I think I can get this working, let me try.

**Comment by taviso** [comment]
I think it works now!
