### ISSUE TITLE
Build fails on Fedora 24

### ISSUE THREAD

**Issue by jpdonnell** [taviso/loadlibrary#8]
make
cc -O3 -march=native -ggdb3 -m32 -std=gnu99 -fshort-wchar -Wno-multichar -Iinclude -DNDEBUG -D_GNU_SOURCE -I. -Iintercept -Ipeloader  -c -o mpclient.o mpclient.c
In file included from /usr/include/features.h:392:0,
                 from /usr/include/stdio.h:27,
                 from mpclient.c:19:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
                      ^

**Comment by taviso** [comment]
I tested on Fedora, and `glibc-devel.i686` and `libgcc.i686` seemed to be enough, have you installed those?

**Comment by jpdonnell** [comment]
Yes 
dnf install glibc-devel libgcc readline-devel cabextract
Last metadata expiration check: 1:20:49 ago on Wed May 24 07:26:52 2017.
Package glibc-devel-2.23.1-11.fc24.x86_64 is already installed, skipping.
Package libgcc-6.3.1-1.fc24.x86_64 is already installed, skipping.
Package libgcc-6.3.1-1.fc24.i686 is already installed, skipping.
Dependencies resolved.
================================================================================
 Package                Arch           Version             Repository      Size
================================================================================
Installing:
 cabextract             x86_64         1.5-4.fc24          fedora          48 k
 readline-devel         x86_64         6.3-8.fc24          fedora         179 k

**Comment by taviso** [comment]
Ah, the `.i686` part is important - because the dll is 32bit we need the 32bit libraries, try this:

`dnf install glibc-devel.i686 glibc-devel.i686`

**Comment by jpdonnell** [comment]
Excellent . Thank you 
JD
