### ISSUE TITLE
Invalid address in function InterlockedCompareExchange

### ISSUE THREAD

**Issue by linhlhq** [taviso/loadlibrary#80]
Hi, I used to load the dll, and have modified some windows api as follows:
```
static LONG InterlockedCompareExchange(PULONG Destination, LONG Exchange, LONG Comparand)
{
    DebugLog("%p", Destination);
    return __sync_val_compare_and_swap(Destination,Exchange,Comparand);
}

STATIC LONG WINAPI InterlockedExchange(PULONG Target, LONG Value){
    return __sync_lock_test_and_set(Target,Value);
}
```
However, when running the debug InterlockedCompareExchange function, the parameter passed to the Termination is an invalid address 0x18.
<img width="756" alt="Screen Shot 2020-03-29 at 8 48 03 PM" src="https://user-images.githubusercontent.com/28854132/77850736-a578a300-71fe-11ea-800f-7e0c955a03bd.png">
Please help me fix this error.
Of course the dll works well on windows. I only used to call the DllMain function and there was an error like the above.

**Comment by taviso** [comment]
Hmm it looks correct to me, the invalid pointer must have come from somewhere else before it reached `InterlockedCompareExchange`. Do you know what the pointer was supposed to be from?

**Comment by linhlhq** [comment]
It looks like your project will only fit into some dlls, not all. I debug and see where the error is. But obviously that location works smoothly on windows. It is hard to understand why it parse the wrong address.
