### ISSUE TITLE
Engine Version: 1.1.17300.4 (2020-07-30) breaks mpclient.

### ISSUE THREAD

**Issue by dstruck** [taviso/loadlibrary#82]
The new engine version 1.1.17300.4 released 2020-07-30 breaks mpclient, this is the error message:

```
./mpclient test.txt
mpclient: function at 0x5a3f5734 attempted to call an unknown symbol
Trace/breakpoint trap
```

**Comment by taviso** [comment]
Thanks for the report, I'm investigating!

**Comment by taviso** [comment]
I *think* this was an easy fix, please verify if it's working!

**Comment by dstruck** [comment]
I confirm that the fix works. Thank you.

**Comment by Ronniexie** [comment]
> I confirm that the fix works. Thank you.

I should make mpclient again?

**Comment by dstruck** [comment]
> > I confirm that the fix works. Thank you.
> 
> I should make mpclient again?

Yes, you must build the binaries again.
