### ISSUE TITLE
Engine Version: 1.1.17400.5 (2020-08-19) breaks mpclient.

### ISSUE THREAD

**Issue by dstruck** [taviso/loadlibrary#84]
The new engine version 1.1.17400.5 released 2020-08-19 breaks mpclient, this is the error message:

```
./mpclient test.txt
main(): Scanning test.txt...
mpclient: function at 0x5a834ec1 attempted to call an unknown symbol
Trace/breakpoint trap
```

**Comment by taviso** [comment]
Thanks for letting me know! I think I've fixed it, just a few new imports: `GetTickCount64()`, and `AcquireSRWLockShared()`. I've just stubbed them out.

**Comment by dstruck** [comment]
Thank you :-)

I can confirm that the patch fixed the issue.
