### ISSUE TITLE
Error: floating point exception (core dumped) in OS and Illegal instruction (core dumped) in Docker

### ISSUE THREAD

**Issue by tldale** [taviso/loadlibrary#92]
Hello,

Running something like "./mpclient winrar-x64-600.exe" in the OS returns a "Floating point exception (core dumped)" error and running this inside of docker it returns a "Illegal instruction (core dumped)" error. 

I've tried this in CentOS7, Ubuntu 18.04 and Ubuntu 20.04. 

In fact for the OS side you don't even have to enter a file name to get the error:

root@ubuntu1804:/opt/loadlibrary# ./mpclient
Floating point exception (core dumped)
root@ubuntu1804:/opt/loadlibrary# ./mpclient /bin/sh
Floating point exception (core dumped)

Anyone else having this issue??

**Comment by godfriedmeesters** [comment]
I have the same issue, inside and outside Docker I get this issue:

 ./mpclient yitaly.exe
Floating point exception (core dumped)

**Comment by taviso** [comment]
Thanks for letting me know, it looks like an update in the last few days broke it.

I'm looking into it.

**Comment by taviso** [comment]
Please try now - this might fix it.

The problem was it was trying to time some function, but I had just stubbed the QueryPerformanceCounters and so on out, so they always returned zero. So when it was calculating how long it took, it was dividing by zero 😂

I've tried to map them on to clock_gettime(), so it should return sensible numbers now.

**Comment by godfriedmeesters** [comment]
Thanks working now!

**Comment by tldale** [comment]
I'm still getting the following in a docker container:

$ ./mpclient
Illegal instruction (core dumped)


also there is no seccomp rules applied:

root@ubuntu1804:~# docker ps --quiet --all | xargs docker inspect --format '{{ .Id }}: SecurityOpt={{ .HostConfig.SecurityOpt }}'
c12350d939d874950bd6218cafdf086df2d5434776b3e84522e1793217897db0: SecurityOpt=[seccomp=unconfined apparmor=unconfined label=disable]


thanks!

**Comment by taviso** [comment]
Hmm, could you find out what it's crashing on?

Run `gdb --args ./mpclient`, then type `run`.

When it crashes, type this:

`x/i $pc` then `i r` and paste the output.
